name: t_utils
description: "A new Flutter package project."
version: 0.0.3
homepage:

environment:
  sdk: ^3.5.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter


  get: ^4.6.6
  intl: ^0.19.0
  iconsax: ^0.0.8
  shimmer: ^3.0.0
  get_storage: ^2.1.1
  url_launcher: ^6.3.0
  connectivity_plus: ^6.0.5
  device_info_plus: ^10.1.2
  country_code_picker: ^3.0.0
  cached_network_image: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


# The following section is specific to Flutter packages.
flutter:
